--  FISH_NAME별 최대 LENGTH 구하고, 그에 해당하는 행을 가져오려면 서브쿼리 사용
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (B.FISH_NAME, A.LENGTH) IN (
    SELECT B2.FISH_NAME, MAX(A2.LENGTH)
    FROM FISH_INFO A2
    JOIN FISH_NAME_INFO B2 ON A2.FISH_TYPE = B2.FISH_TYPE
    GROUP BY B2.FISH_NAME
)
ORDER BY A.ID;