SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE' -- 개별 행 조건은 WHERE
GROUP BY B.USER_ID
HAVING SUM(A.PRICE)>= 700000 -- 그룹 조건은 HAVING
ORDER BY TOTAL_SALES;