SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD A
    JOIN USED_GOODS_FILE B
    ON A.BOARD_ID = B.BOARD_ID
-- 조회수가 가장 높은 게시글이 "1개"만 존재해야 의미가 정확함
WHERE A.BOARD_ID = (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)
ORDER BY B.FILE_ID DESC