SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS M -- FOOD_TYPE별 최대 FAVORITES를 구하고
ON R.FOOD_TYPE = M.FOOD_TYPE AND R.FAVORITES = M.MAX_FAV -- 원본 테이블과 JOIN하여 정확히 그 값을 가진 ROW만 추출
ORDER BY R.FOOD_TYPE DESC;