SELECT 
    COUNT(ID) AS FISH_COUNT,
    MAX(CASE WHEN LENGTH IS NULL OR LENGTH <= 10 THEN 10 ELSE LENGTH END) AS MAX_LENGTH,  -- 집계함수 안에 CASE문
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(CASE WHEN LENGTH IS NULL OR LENGTH <= 10 THEN 10 ELSE LENGTH END) >= 33 -- ELSE LENGTH를 써서 NULL 방지
ORDER BY FISH_TYPE;

-- LENGTH가 NULL인 경우, 10 이하인 경우 둘 다 10으로 대체