SELECT 
    A.YEAR,
    B.MAX_SIZE - A.SIZE_OF_COLONY YEAR_DEV, 
    A.ID
FROM (
    SELECT *, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
) A
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) B ON A.YEAR = B.YEAR
ORDER BY A.YEAR, YEAR_DEV;