SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = ( -- 메인 쿼리에서 그 사람의 리뷰들을 조회
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID -- 가장 많이 쓴 사람 찾기
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;