-- 이렇게 풀 수도 있지만
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_OUTCOME LIKE 'Intact%' 
AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID;


-- 정규표현식 사용
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE REGEXP_LIKE(I.SEX_UPON_INTAKE, '^Intact')
  AND REGEXP_LIKE(O.SEX_UPON_OUTCOME, '^(Spayed|Neutered)')
ORDER BY I.ANIMAL_ID;