SELECT f.FLAVOR
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_QTY
     FROM FIRST_HALF
     GROUP BY FLAVOR) f -- 상반기 주문량 합산
INNER JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_QTY
     FROM JULY
     GROUP BY FLAVOR) j -- 7월 주문량 합산
ON f.FLAVOR = j.FLAVOR -- FLAVOR 기준으로 합치기
ORDER BY (f.TOTAL_QTY + j.TOTAL_QTY) DESC LIMIT 3; -- 합산 주문량 기준 내림차순